[package]
name = "rofl-ls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
byteorder = "1.4.3"
libflate = "1"
itertools = "0.10.1"
structopt = "0.3"
